apiVersion: v1
kind: Service
metadata:
  name: photoprism-service
  labels:
    app: photoprism
spec:
  type: ClusterIP
  selector:
    app: photoprism
  ports:
  - name: http
    port: 2342
    targetPort: 2342
 #   nodePort: 31861 
